### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by knightjp** [Conky-for-macOS/conky-for-macOS#23]
I am not a developer. Could I have a detailed step by step instruction to install it? 

I saw a video on youtube but I can't follow or understand it. 

[https://www.youtube.com/watch?v=l3tIiDdnC68](url)

**Comment by npyl** [comment]
Hi,
hope this helps:

## Installation

You first need to download and install the following software:

- [Homebrew](https://brew.sh)
- [XQuartz](https://www.xquartz.org)
- [ConkyX app](https://github.com/Conky-for-macOS/ConkyX/releases/tag/0.0.0.6.3-nearl1)
- ( There is some more software but don't worry because ConkyX installs it for you! )

For installing ConkyX, please unzip the downloaded file and run ConkyX.app.

ConkyX.app will ask to be installed in /Applications and if you hit YES, it will close and rerun.
It will check if the required software is missing, and if so, it will install it.  This may take some 
minutes.

Once this finishes, you are ready to use conky!

(OOPS: I just remembered that I bundle conky inside ConkyX.app, thus you won't be able to use conky from the command line.  To amend this problem, you can add the command: 
`echo "export PATH=/Applications/ConkyX.app/Contents/Resources:\$PATH" > ~/.profile`
and restart your terminal! This won't be necessary in the next version of ConkyX.)

## Configuration

If you want to configure a bit conky, you can download [Manage Conky.app](https://github.com/Conky-for-macOS/Manage-Conky/releases) which allows:

- Choosing to run/not run conky on startup
- Uninstalling ConkyX and Manage Conky

**Comment by knightjp** [comment]
Does this work with High Sierra?

**Comment by npyl** [comment]
Yes it does!
Just make sure to download **version 0.0.0.6.4** of ConkyX because I published a new yesterday and the installation process will be slightly different.

**Comment by npyl** [comment]
A complete list of what is supported will be uploaded in the future, but here is a quick look of what is supported: 
- memory stats (memstats branch, not master)
- cpu stats (not per cpu, but per whole processor, per cpu is really easy to implement though)
- per process cpu,memory % usage
- total processes, threads count
- uptime
- ckecking if mounted/ if exists
- many more...

**Comment by npyl** [comment]
Installation steps have been simplified and an updated guide has been published [here](https://github.com/Conky-for-macOS/conky-for-macOS/wiki/How-to-install)
